import type { Metadata } from 'next';

import { Providers } from '@components';
import { inter } from '@constants';

import './globals.css';
import { getSession } from './api/auth/[...nextauth]/route';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();

  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <Providers session={session}>{children}</Providers>
      </body>
    </html>
  );
}
